kind: Deployment
apiVersion: apps/v1
metadata: 
  name: rabbitmq-deployment
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: {{ .Values.image }}
        ports:       
        - containerPort: {{ .Values.port }}
        - containerPort: {{ .Values.stompPort }}

      imagePullSecrets:
      - name: regcred 

  
---
kind: Service
apiVersion: v1
metadata:
  name: rabbitmq-service
spec:
  selector:
    app: rabbitmq
  type: LoadBalancer
  ports: 
  - name: port-5672
    protocol: TCP
    port: {{ .Values.port }}
    targetPort: {{ .Values.port }}
  - name: port-61613
    protocol: TCP
    port: {{ .Values.stompPort }}
    targetPort: {{ .Values.stompPort }}
