{{- if .Values.global.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: apigateway-service
  namespace: {{ .Release.Namespace }}
  labels: 
    app: auth
    {{- include "decisionlens.labels" . | nindent 4 }}
  annotations: {}
{{- end  }}
