kind: Deployment
apiVersion: apps/v1
metadata: 
  name: apigateway-deployment
  labels:
    app: apigateway
    {{- include "decisionlens.labels" . | nindent 4 }}
  annotations:
  {{- with .Values.global.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.service.apigateway.replicas }}
  selector:
    matchLabels:
      app: apigateway
      {{- include "decisionlens.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: apigateway
        {{- include "decisionlens.selectorLabels" . | nindent 8 }}
      annotations:
      {{- with .Values.global.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
      - name: apigateway
        image: {{ .Values.service.image.url }}/{{ .Values.service.apigateway.tag }}
        resources:
          requests:
            memory: "1000Mi"
            cpu: "1000m"
          limits:
            memory: "4000Mi"
            cpu: "2000m"
        ports:
        - containerPort: {{ .Values.service.apigateway.port }}           
        env: 
        - name: service.url.integration
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-configmap
              key: integration-service-url
              
        - name: service.url.portfolio
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-configmap
              key: portfolio-service-url  

        - name: service.url.mldata
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-configmap
              key: mldata-service-url 

        - name: service.url.plan
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-configmap
              key: plan-service-url   

        - name: service.url.messaging
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-configmap
              key: messaging-service-url  

        - name: service.url.auth
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-configmap
              key: auth-service-url  

        - name: service.url.dlc
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-configmap
              key: dlc-service-url  
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: apigateway-service
      {{- end }}
      imagePullSecrets:
      {{- with .Values.global.imagePullSecrets }}
      {{- toYaml . | nindent 6 }}
      {{- end }}

