---
kind: Service
apiVersion: v1
metadata:
  name: auth-service
  labels: 
    app: auth
    {{- include "decisionlens.labels" . | nindent 4 }}
  {{- with .Values.service.auth.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    app: auth
    {{- include "decisionlens.selectorLabels" . | nindent 4 }}
  {{- with .Values.service.auth.selectorLabels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.auth.port }} 
    targetPort: {{ .Values.service.auth.port }}

