{{- if .Values.global.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-service
  namespace: {{ .Release.Namespace }}
  labels: {{- include "decisionlens.labels.standard" . | nindent 4 }}
    app: auth
  annotations: {}
{{- end  }}
