kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-configmap
  labels:
    {{- include "decisionlens.labels" . | nindent 4 }}
data: 
  database-host: {{ .Values.database.host | quote }}
  database-port: {{ .Values.database.port | quote }}
  dlc-database-name: {{ .Values.database.dlc | quote }}
  memcached-service-url: {{ .Values.memcached.servers }}
  elastic-service-url: {{ .Values.elastic.server.url }}
  rabbitmq-host: {{ .Values.rabbitmq.host }}
  rabbitmq-port: {{ .Values.rabbitmq.port | quote }}
  rabbitmq-stompPort: {{ .Values.rabbitmq.stompPort | quote }}
  mail-host: {{ .Values.mail.host }}
  mail-port: {{ .Values.mail.port | quote }}
  mail-auth: {{ .Values.mail.auth | quote }}
  dlx-api-url: {{ .Values.dlx.api.url | quote }}
  apigateway-service-url: {{ .Values.service.apigateway.url | quote }}
  integration-service-url: {{ .Values.service.integration.url | quote }}
  portfolio-service-url: {{ .Values.service.portfolio.url  | quote}}
  plan-service-url: {{ .Values.service.plan.url | quote }}
  messaging-service-url: {{ .Values.service.messaging.url | quote }}
  auth-service-url: {{ .Values.service.auth.url  | quote}}
  dlc-service-url: http://dlc-service:{{ .Values.service.dlc.port }}
  client-id: {{ .Values.dlx.ui.clientId | quote }}
  access-token-header: {{ .Values.access.token.header | quote }}
  config.json: |
    {
       "api": {
          "defaultServiceUrl": {{ .Values.dlx.api.url | quote }}
       },
       "auth": {
          "clientId": {{ .Values.dlx.ui.clientId | quote }},
          "authServiceUrl": {{ .Values.dlx.api.url | quote }},
          "accessTokenHeader": {{ .Values.access.token.header | quote }}    
       },
       "analytics": { 
         "pendoEnabled": {{ .Values.analytics.pendo }},
         "googleAnalyticsEnabled": {{ .Values.analytics.google }}
       }
    }

