---
kind: Service
apiVersion: v1
metadata:
  name: dlc-service
  labels:
    app: dlc
    {{- include "decisionlens.labels" . | nindent 4 }}
  {{- with .Values.service.dlc.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    app: dlc
    {{- include "decisionlens.selectorLabels" . | nindent 4 }}
  {{- with .Values.service.dlc.selectorLabels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.dlc.port }}
    targetPort: {{ .Values.service.dlc.port }}
