kind: Deployment
apiVersion: apps/v1
metadata:
  name: dlc-deployment
  labels:
    app: dlc
    {{- include "decisionlens.labels" . | nindent 4 }}
  {{- with .Values.service.dlc.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  annotations:
  {{- with .Values.global.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.service.dlc.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.service.dlc.replicas }}
  selector:
    matchLabels:
      app: dlc
      {{- include "decisionlens.selectorLabels" . | nindent 6 }}
    {{- with .Values.service.dlc.selectorLabels }}
      {{- toYaml . | nindent 6 }}
    {{- end }}
  template:
    metadata:
      labels:
        app: dlc
        {{- include "decisionlens.selectorLabels" . | nindent 8 }}
      {{- with .Values.service.dlc.selectorLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      annotations:
      {{- with .Values.global.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.service.dlc.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      volumes:
      {{- if .Values.jwt.publicKey }}
      - name: jwt-keys-volume
        secret:
          secretName: jwt-keys-secret
      {{- end }}
      {{- if .Values.service.dlc.extraVolumes -}}
      {{ toYaml .Values.service.dlc.extraVolumes | nindent 6 }}
      {{- end }}
      containers:
      - name: dlc
        image: {{ .Values.service.image.url }}/{{ .Values.service.dlc.tag }}
        resources:
          requests:
            memory: {{ .Values.service.dlc.resources.requests.memory }}
            cpu: {{ .Values.service.dlc.resources.requests.cpu }}
          limits:
            memory: {{ .Values.service.dlc.resources.limits.memory }}
            cpu: {{ .Values.service.dlc.resources.limits.cpu }}
        ports:
        - containerPort: {{ .Values.service.dlc.port }}
        imagePullPolicy: Always
        volumeMounts:
        {{- if .Values.jwt.publicKey }}
        - name: jwt-keys-volume
          readOnly: true
          mountPath: /jwt-keys
        {{- end }}
        {{- if .Values.service.dlc.extraVolumeMounts -}}
        {{ toYaml .Values.service.dlc.extraVolumeMounts | nindent 8 }}
        {{- end }}
        env:
        - name: database.jdbcUrl
          value: jdbc:mysql://{{ .Values.database.host }}:{{ .Values.database.port }}/{{ .Values.database.dlc }}?{{ include "decisionlens.dlc.jdbc.options" . }}
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secret
              key: database-username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secret
              key: database-password
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-configmap
              key: database-host
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-configmap
              key: database-port
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-configmap
              key: dlc-database-name
        - name: service.url.apigateway
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-configmap
              key: apigateway-service-url
        - name: database.jdbcUrl
          value: jdbc:mysql://{{ .Values.database.host }}:{{ .Values.database.port }}/dl3?{{ include "decisionlens.jdbc.options" . }}
        - name: database.username
          valueFrom:
            secretKeyRef:
              name: { { .Release.Name } }-secret
              key: database-username
        - name: database.password
          valueFrom:
            secretKeyRef:
              name: { { .Release.Name } }-secret
              key: database-password
        - name: database.dlconf.jdbcUrl
          value: jdbc:mysql://{{ .Values.database.host }}:{{ .Values.database.port }}/dlconf?{{ include "decisionlens.jdbc.options" . }}
        - name: database.dlconf.username
          valueFrom:
            secretKeyRef:
              name: { { .Release.Name } }-secret
              key: database-username
        - name: database.dlconf.password
          valueFrom:
            secretKeyRef:
              name: { { .Release.Name } }-secret
              key: database-password
        - name: cacheServers
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-configmap
              key: memcached-service-url
        - name: elastic.server
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-configmap
              key: elastic-service-url
        - name: jwt.secret
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secret
              key: jwt-secret
        - name: spring.rabbitmq.host
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-configmap
              key: rabbitmq-host
        - name: spring.rabbitmq.port
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-configmap
              key: rabbitmq-stompPort
        - name: spring.rabbitmq.username
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secret
              key: rabbitmq-username
        - name: spring.rabbitmq.password
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secret
              key: rabbitmq-password
        - name: DL_LICENSE_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secret
              key: dl-license-key
        - name: spring.mail.host
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-configmap
              key: mail-host
        - name: spring.mail.port
          valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-configmap
                key: mail-port
        - name: spring.mail.username
          valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-secret
                key: mail-username
        - name: spring.mail.password
          valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-secret
                key: mail-password
        - name: spring.mail.properties.mail.smtp.auth
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-configmap
              key: mail-auth
        - name: access.token.header
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-configmap
              key: access-token-header
        {{- if .Values.jwt.publicKey -}}
        - name: jwt.privateKey
          value: /jwt-keys/private_key.pk8
        - name: jwt.publicKey
          value: /jwt-keys/public_key.pub
        {{- end }}
        {{- if .Values.service.dlc.extraEnv -}}
        {{ toYaml .Values.service.dlc.extraEnv | nindent 8 }}
        {{- end }}
      {{- if .Values.global.serviceAccount.create }}
      serviceAccountName: dlc-service
      {{- end }}
      imagePullSecrets:
      {{- range .Values.global.imagePullSecrets }}
      - name: {{ . }}
      {{- end }}


