---
kind: Service
apiVersion: v1
metadata:
  name: dlcui-service
  {{- include "decisionlens.labels" . | nindent 2 }}
spec:
  selector:
    app: dlcui
    {{- include "decisionlens.labels" . | nindent 4 }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.dlcui.port }}
    targetPort: {{ .Values.service.dlcui.port }}

