kind: Deployment
apiVersion: apps/v1
metadata: 
  name: dlcui-deployment
  labels:
    app: dlcui
    {{- include "decisionlens.labels.standard" . | nindent 4 }}
  annotations:
  {{- with .Values.global.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.service.dlcui.replicas }}
  selector:
    matchLabels:
      app: dlcui
      {{- include "decisionlens.labels.standard" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: dlcui
        {{- include "decisionlens.labels.standard" . | nindent 8 }}
      annotations:
      {{- with .Values.global.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:      
      containers:
      - name: dlcui
        image: {{ .Values.service.image.url }}/{{ .Values.service.dlcui.tag }}
        resources:
          requests:
            memory: "1000Mi"
            cpu: "1000m"
          limits:
            memory: "4000Mi"
            cpu: "2000m"
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.service.dlcui.port }}
        env:
        - name: CLIENT_ID
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-configmap
              key: client-id
        - name: DLC_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-configmap
              key: dlc-service-url
        - name: AUTH_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-configmap
              key: dlx-api-url
      {{- if .Values.global.serviceAccount.create }}
      serviceAccountName: dlcui-service
      {{- end }}
      imagePullSecrets:
      {{- with .Values.global.imagePullSecrets }}
      {{- toYaml . | nindent 6 }}
      {{- end }}


