kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: dlx-ingress
  labels:
    {{- include "decisionlens.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    {{- with .Values.ingress.dlx.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: nginx
  rules:
  - host: dlx
    http:
      paths:
      - path: "/v1"
        pathType: Prefix
        backend:
          service:
            name: apigateway-service
            port:
              number: {{ .Values.service.apigateway.port }}

      - path: "/oauth/callback"
        pathType: Prefix
        backend:
          service:
            name: dlxui-service
            port:
              number: {{ .Values.service.dlxui.port }}

      - path: "/oauth"
        pathType: Prefix
        backend:
          service:
            name: apigateway-service
            port:
              number: {{ .Values.service.apigateway.port }}

      - path: "/.*-service"
        pathType: Prefix
        backend:
          service:
            name: apigateway-service
            port:
              number: {{ .Values.service.apigateway.port }}

      - path: "/"
        pathType: Prefix
        backend:
         service:
            name: dlxui-service
            port:
              number: {{ .Values.service.dlxui.port }}

