kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: dlx-ingress
  labels:
    {{- include "decisionlens.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    {{- with .Values.ingress.dlx.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  {{- if .Values.ingress.dlx.tls }}
  tls:
  {{- range .Values.ingress.dlx.tls }}
  - hosts:
    {{- range .hosts }}
    - {{ .host | quote }}
    {{- end }}
    secretName: {{ .secretName }}
  {{- end }}
  {{- end }}
  rules:
  {{- range .Values.ingress.dlx.hosts }}
  - host: {{ .host | quote }}
    http:
      paths:
      {{- range .paths }}
      - path: {{ .path | quote }}
        pathType: {{ .pathType }}
        backend:
          service:
            name: {{ .serviceName }}
            port:
              number: {{ .port }}
      {{- end -}}
  {{- end }}

