{{- if .Values.global.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dlxui-service
  namespace: {{ .Release.Namespace }}
  labels: 
    app: dlx
    {{- include "decisionlens.labels.standard" . | nindent 4 }}
  annotations: {}
{{- end  }}
