---
kind: Service
apiVersion: v1
metadata:
  name: integration-service
  labels:
    app: integration
    {{- include "decisionlens.labels.standard" . | nindent 4 }}
spec:
  selector:
    app: integration
    {{- include "decisionlens.labels.standard" . | nindent 4 }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.integration.port }} 
    targetPort: {{ .Values.service.integration.port }}

