---
kind: Service
apiVersion: v1
metadata:
  name: messaging-service
  labels:
    app: messaging
    {{- include "decisionlens.labels.standard" . | nindent 4 }}
spec:
  selector:
    app: messaging
    {{- include "decisionlens.labels.standard" . | nindent 4 }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.messaging.port }} 
    targetPort: {{ .Values.service.messaging.port }}

