{{- if .Values.global.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name:  messaging-service
  namespace: {{ .Release.Namespace }}
  labels: 
    app: messaging
    {{- include "decisionlens.labels" . | nindent 4 }}
  annotations: {}
{{- end  }}
