{{- if .Values.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name:  mldata-service
  namespace: {{ .Release.Namespace }}
  labels: 
    app: mldata
    {{- include "decisionlens.labels.standard" . | nindent 4 }}
  annotations: {}
{{- end  }}
