---
kind: Service
apiVersion: v1
metadata:
  name: plan-service
  labels:
    app: plan
    {{- include "decisionlens.labels.standard" . | nindent 4 }}
spec:
  selector:
    app: plan
    {{- include "decisionlens.labels.standard" . | nindent 4 }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.plan.port }} 
    targetPort: {{ .Values.service.plan.port }}

