kind: Deployment
apiVersion: apps/v1
metadata: 
  name: portfolio-deployment
  labels:
    app: portfolio
    {{- include "decisionlens.labels" . | nindent 4 }}
  {{- with .Values.service.portfolio.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  annotations:
  {{- with .Values.global.annotations }}
    {{- toYaml . | nindent 6 }}
  {{- end }}
  {{- with .Values.service.portfolio.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.service.portfolio.replicas }}
  selector:
    matchLabels:
      app: portfolio
      {{- include "decisionlens.selectorLabels" . | nindent 6 }}
    {{- with .Values.service.portfolio.selectorLabels }}
      {{- toYaml . | nindent 6 }}
    {{- end }}
  template:
    metadata:
      labels:
        app: portfolio
        {{- include "decisionlens.selectorLabels" . | nindent 8 }}
      {{- with .Values.service.portfolio.selectorLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      annotations:
      {{- with .Values.global.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.service.portfolio.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      volumes:
      {{ if .Values.jwt.publicKey }}
      - name: jwt-keys-volume
        secret:
          secretName: jwt-keys-secret
      {{ end }}
      {{- if .Values.service.portfolio.extraVolumes -}}
      {{ toYaml .Values.service.portfolio.extraVolumes | nindent 6 }}
      {{- end }}
      containers:
      - name: portfolio
        image: {{ .Values.service.image.url }}/{{ .Values.service.portfolio.tag }}
        resources:
          requests:
            memory: {{ .Values.service.portfolio.resources.requests.memory }}
            cpu: {{ .Values.service.portfolio.resources.requests.cpu }}
          limits:
            memory: {{ .Values.service.portfolio.resources.limits.memory }}
            cpu: {{ .Values.service.portfolio.resources.limits.cpu }}
        ports:
        - containerPort: {{ .Values.service.portfolio.port }}    
        imagePullPolicy: Always
        volumeMounts:
        {{ if .Values.jwt.publicKey }}
        - name: jwt-keys-volume
          readOnly: true
          mountPath: /jwt-keys
        {{ end }}
        {{- if .Values.service.portfolio.extraVolumeMounts -}}
        {{ toYaml .Values.service.portfolio.extraVolumeMounts | nindent 8 }}
        {{- end }}
        env:        
        - name: service.url.apigateway
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-configmap
              key: apigateway-service-url
        - name: database.jdbcUrl
          value: jdbc:mysql://{{ .Values.database.host }}:{{ .Values.database.port }}/portfolio?{{ include "decisionlens.jdbc.options" . }}
        - name: database.username
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secret
              key: database-username
        - name: database.password
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secret
              key: database-password
        - name: database.dlconf.jdbcUrl
          value: jdbc:mysql://{{ .Values.database.host }}:{{ .Values.database.port }}/dlconf?{{ include "decisionlens.jdbc.options" . }}
        - name: database.dlconf.username
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secret
              key: database-username
        - name: database.dlconf.password
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secret
              key: database-password
        - name: cacheServers
          valueFrom:
            configMapKeyRef: 
              name: {{ .Release.Name }}-configmap
              key: memcached-service-url
        - name: elastic.server
          valueFrom:
            configMapKeyRef: 
              name: {{ .Release.Name }}-configmap
              key: elastic-service-url
        - name: jwt.secret
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secret
              key: jwt-secret
        - name: spring.rabbitmq.host
          valueFrom: 
            configMapKeyRef: 
              name: {{ .Release.Name }}-configmap
              key: rabbitmq-host
        - name: spring.rabbitmq.port
          valueFrom: 
            configMapKeyRef: 
              name: {{ .Release.Name }}-configmap
              key: rabbitmq-port
        - name: spring.rabbitmq.username
          valueFrom: 
            secretKeyRef: 
              name: {{ .Release.Name }}-secret
              key: rabbitmq-username
        - name: spring.rabbitmq.password
          valueFrom: 
            secretKeyRef: 
              name: {{ .Release.Name }}-secret
              key: rabbitmq-password
        - name: DL_LICENSE_KEY
          valueFrom: 
            secretKeyRef: 
              name: {{ .Release.Name }}-secret
              key: dl-license-key
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secret
              key: database-username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secret
              key: database-password
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-configmap
              key: database-host
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-configmap
              key: database-port
        - name: access.token.header
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-configmap
              key: access-token-header
        {{ if .Values.jwt.publicKey }}
        - name: jwt.privateKey
          value: /jwt-keys/private_key.pk8
        - name: jwt.publicKey
          value: /jwt-keys/public_key.pub
        {{ end }}
        {{- if .Values.service.portfolio.extraEnv -}}
        {{ toYaml .Values.service.portfolio.extraEnv | nindent 8 }}
        {{- end }}
      {{- if .Values.global.serviceAccount.create }}
      serviceAccountName: portfolio-service
      {{- end }}
      imagePullSecrets:
      {{- range .Values.global.imagePullSecrets }}
      - name: {{ . }}
      {{- end }}


