---
kind: Service
apiVersion: v1
metadata:
  name: portfolio-service
  labels:
    app: portfolio
    {{- include "decisionlens.labels" . | nindent 4 }}
  {{- with .Values.service.portfolio.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    app: portfolio
    {{- include "decisionlens.selectorLabels" . | nindent 4 }}
  {{- with .Values.service.portfolio.selectorLabels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.portfolio.port }} 
    targetPort: {{ .Values.service.portfolio.port }}

