kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    {{- include "decisionlens.labels" . | nindent 4 }}
type: Opaque
data:
  database-username: {{ .Values.database.username | b64enc }}
  database-password: {{ .Values.database.password | b64enc }}
  jwt-secret: {{ .Values.jwt.secret | b64enc }}
  rabbitmq-username: {{ .Values.rabbitmq.username | b64enc }}
  rabbitmq-password: {{ .Values.rabbitmq.password | b64enc }}
  mail-username: {{ .Values.mail.username | b64enc }}
  mail-password: {{ .Values.mail.password | b64enc }}
  dl-license-key: {{ .Values.license.key | b64enc }}
